name: frontend
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  intl: 0.17.0
  bubble_tab_indicator: "0.1.5"
  material_design_icons_flutter: 5.0.6996
  shared_preferences: 2.0.15
  group_button: ^5.2.2
  google_fonts: 2.3.0
  group_radio_button: 1.2.0
  font_awesome_flutter: ^10.2.1
  ndialog: 4.2.0
  screen_loader: 4.0.1
  grouped_list: ^5.1.2
  http: 0.13.3
  provider: ^6.0.4
  flutter_spinkit: 5.1.0
  jwt_decode: 0.3.1
  flutter_secure_storage: ^6.0.0
  flutter_slidable: 1.3.2
  currency_text_input_formatter: 2.1.7
  infinite_scroll_pagination: ^3.2.0
  get_it: 7.2.0
  dots_indicator: 2.1.0
  flutter_phoenix: 1.0.0
  introduction_screen: 2.1.0
  file_picker: ^4.3.0
  cupertino_icons: 1.0.2
  connectivity_plus: 2.0.2
  sizer: 2.0.15
  editable: 2.0.0
  fl_chart: 0.55.2
  syncfusion_flutter_charts: 19.4.56
  http_interceptor: 1.0.2
  reflectable: 3.0.8
  animated_icon_button: 1.0.2
  chips_choice_null_safety: ^2.0.6
  data_table_2: 2.2.1
  package_info_plus: ^1.4.0
  json_annotation: ^4.5.0
  reactive_forms: ^10.7.0
  cached_network_image: ^3.2.0
  collection: ^1.15.0
  flutter_cache_manager: ^3.3.0
  path: ^1.8.0
  path_provider: ^2.0.9
  pub_semver: ^2.1.1
  scrollable_positioned_list: ^0.2.3
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
